id: I8E707B72
legacy_id: P006710
ocr_import_info:
  bdrc_scan_id: W00EGS1016273
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T19:13:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T12:49:56.572123+00:00'
last_modified: 2022-08-30 20:51:37.802739
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016273
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016273
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀྲ་ཤིས་སྒོ་མང་གི་མཁས་དབང་དག་གི་གསུང་དེང་དུས་དཔེ་རྒྱུན་ཤིན་ཏུ་དཀོན་པ་རྣམས་ལས་འདིར་གང་བྱུང་ཞིག་ཕྱོགས་བསྡུས།
statistics:
  ocr_word_mean_confidence_index: 0.7327591047208016
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I00JW501152:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501152
      total_pages: 622
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00JW501152.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.762487858378549
    legacy_id: v001
  I00JW501153:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00JW501153
      total_pages: 600
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00JW501153.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.7024770299324234
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
