id: P006710
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1016273
  title: བཀྲ་ཤིས་སྒོ་མང་གི་མཁས་དབང་དག་གི་གསུང་དེང་དུས་དཔེ་རྒྱུན་ཤིན་ཏུ་དཀོན་པ་རྣམས་ལས་འདིར་གང་བྱུང་ཞིག་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    e42bd57756d84565bcfd64fe16605da7:
      image_group_id: I00JW501152
      title: ''
      volume_number: 1
      total_pages: 622
      base_file: v001.txt
    68551a03ec7e4564a28ec83d9755e695:
      image_group_id: I00JW501153
      title: ''
      volume_number: 2
      total_pages: 600
      base_file: v002.txt
