id: P006710
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016273
  title: བཀྲ་ཤིས་སྒོ་མང་གི་མཁས་དབང་དག་གི་གསུང་དེང་དུས་དཔེ་རྒྱུན་ཤིན་ཏུ་དཀོན་པ་རྣམས་ལས་འདིར་གང་བྱུང་ཞིག་ཕྱོགས་བསྡུས།
  author: ''
  volumes: {}
